# Generated by Django 4.1.2 on 2022-10-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lay_Out_107',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_do_cliente', models.CharField(max_length=9)),
                ('cnpj_cpf_cliente', models.CharField(max_length=11)),
                ('tipo_de_cliente', models.CharField(max_length=2)),
                ('data_do_pregao', models.DateField()),
                ('numero_da_nota', models.CharField(max_length=9)),
                ('assessor', models.CharField(max_length=5)),
                ('vendas_a_vista', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('compras_a_vista', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('opcoes_de_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('opcoes_de_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('outras_operacoes', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('valor_liquido_das_operacoes', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('taxas', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('emolumentos', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('corretagem_liquida', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('corretagem_bruta', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('valor_liquido_da_nota', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('sinal_do_valor_liquido', models.CharField(max_length=1)),
                ('constante', models.CharField(max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lay_Out_108',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_do_cliente', models.CharField(max_length=9)),
                ('cnpj_cpf_cliente', models.CharField(max_length=11)),
                ('tipo_de_cliente', models.CharField(max_length=2)),
                ('data_do_pregao', models.DateField()),
                ('numero_da_nota', models.CharField(max_length=9)),
                ('tipo_do_mercado', models.CharField(max_length=20, null=True)),
                ('compra_venda', models.CharField(max_length=1, null=True)),
                ('especificacao_do_titulo', models.CharField(max_length=30, null=True)),
                ('obs', models.CharField(max_length=3)),
                ('quantidade', models.IntegerField()),
                ('preco_da_liquidacao', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('valor_da_operacao', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('numero_sequencial_da_operacao', models.PositiveIntegerField()),
                ('codigo_da_contraparte', models.CharField(max_length=8)),
                ('constante', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titneg',
            fields=[
                ('codneg', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('codemp', models.CharField(max_length=4)),
                ('densoc', models.CharField(max_length=60)),
                ('nomres', models.CharField(blank=True, max_length=12, null=True)),
                ('dtcria', models.DateTimeField(auto_now_add=True)),
                ('dtatua', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notcor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notcor', models.CharField(max_length=9)),
                ('codneg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.titneg')),
                ('natope', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('dtnota', models.DateField()),
                ('quanti', models.IntegerField()),
                ('pcunit', models.DecimalField(decimal_places=2, max_digits=13)),
                ('corret', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('despes', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('emolum', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('taxliq', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('valliq', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('dtcria', models.DateTimeField(auto_now_add=True)),
                ('dtatua', models.DateTimeField(auto_now=True)),
                
            ],
        ),
    ]
